# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1759fqTBlD5iFUZERzhqVXOYUPTq3RxUZ
"""



# ============================================================
# Advanced Time Series Forecasting with LSTM + Attention
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, LSTM, Dense, Layer
)
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

# ------------------------------------------------------------
# 1. DATA GENERATION (Multivariate, >5000 points)
# ------------------------------------------------------------

np.random.seed(42)
time_steps = 6000
t = np.arange(time_steps)

series_1 = np.sin(0.02 * t) + 0.5 * np.sin(0.05 * t)
series_2 = np.cos(0.015 * t)
noise = np.random.normal(0, 0.1, time_steps)

target = series_1 + series_2 + noise

data = pd.DataFrame({
    "feature_1": series_1,
    "feature_2": series_2,
    "target": target
})

# ------------------------------------------------------------
# 2. PREPROCESSING
# ------------------------------------------------------------

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

LOOK_BACK = 30

def create_sequences(dataset, look_back):
    X, y = [], []
    for i in range(len(dataset) - look_back):
        X.append(dataset[i:i+look_back, :-1])
        y.append(dataset[i+look_back, -1])
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data, LOOK_BACK)

split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# ------------------------------------------------------------
# 3. ATTENTION LAYER (Bahdanau-style)
# ------------------------------------------------------------

class Attention(Layer):
    def __init__(self):
        super(Attention, self).__init__()

    def build(self, input_shape):
        self.W = self.add_weight(
            name="att_weight",
            shape=(input_shape[-1], input_shape[-1]),
            initializer="random_normal",
            trainable=True
        )
        self.b = self.add_weight(
            name="att_bias",
            shape=(input_shape[-1],),
            initializer="zeros",
            trainable=True
        )
        self.u = self.add_weight(
            name="att_u",
            shape=(input_shape[-1], 1),
            initializer="random_normal",
            trainable=True
        )
        super().build(input_shape)

    def call(self, x):
        score = tf.nn.tanh(tf.tensordot(x, self.W, axes=1) + self.b)
        attention_weights = tf.nn.softmax(
            tf.tensordot(score, self.u, axes=1), axis=1
        )
        context_vector = attention_weights * x
        context_vector = tf.reduce_sum(context_vector, axis=1)
        return context_vector, attention_weights

# ------------------------------------------------------------
# 4. ATTENTION-BASED LSTM MODEL
# ------------------------------------------------------------

inputs = Input(shape=(LOOK_BACK, X.shape[2]))
lstm_out = LSTM(64, return_sequences=True)(inputs)
context, attention_weights = Attention()(lstm_out)
output = Dense(1)(context)

attention_model = Model(inputs, output)
attention_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="mse"
)

# ------------------------------------------------------------
# 5. BASELINE LSTM MODEL (NO ATTENTION)
# ------------------------------------------------------------

baseline_model = tf.keras.Sequential([
    LSTM(64, input_shape=(LOOK_BACK, X.shape[2])),
    Dense(1)
])

baseline_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="mse"
)

# ------------------------------------------------------------
# 6. MODEL TRAINING
# ------------------------------------------------------------

history_att = attention_model.fit(
    X_train, y_train,
    epochs=15,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

history_base = baseline_model.fit(
    X_train, y_train,
    epochs=15,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

# ------------------------------------------------------------
# 7. EVALUATION METRICS
# ------------------------------------------------------------

def evaluate(model, X_test, y_test):
    predictions = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    mae = mean_absolute_error(y_test, predictions)
    mape = np.mean(np.abs((y_test - predictions.flatten()) / y_test)) * 100
    return rmse, mae, mape

att_rmse, att_mae, att_mape = evaluate(attention_model, X_test, y_test)
base_rmse, base_mae, base_mape = evaluate(baseline_model, X_test, y_test)

print("\n--- Model Performance Comparison ---")
print(f"Attention Model -> RMSE: {att_rmse:.4f}, MAE: {att_mae:.4f}, MAPE: {att_mape:.2f}%")
print(f"Baseline LSTM  -> RMSE: {base_rmse:.4f}, MAE: {base_mae:.4f}, MAPE: {base_mape:.2f}%")

# ------------------------------------------------------------
# 8. ATTENTION WEIGHT VISUALIZATION
# ------------------------------------------------------------

attention_extractor = Model(
    inputs=attention_model.input,
    outputs=attention_model.layers[2].output
)

_, att_weights = attention_extractor.predict(X_test[:1])
att_weights = att_weights.reshape(LOOK_BACK)

plt.figure(figsize=(10, 4))
plt.bar(range(LOOK_BACK), att_weights)
plt.title("Attention Weights Over Look-back Window")
plt.xlabel("Time Steps")
plt.ylabel("Importance")
plt.show()

# ------------------------------------------------------------
# 9. TRAINING LOSS VISUALIZATION
# ------------------------------------------------------------

plt.figure(figsize=(10, 4))
plt.plot(history_att.history["loss"], label="Attention Train Loss")
plt.plot(history_att.history["val_loss"], label="Attention Val Loss")
plt.plot(history_base.history["loss"], label="Baseline Train Loss")
plt.plot(history_base.history["val_loss"], label="Baseline Val Loss")
plt.legend()
plt.title("Training History Comparison")
plt.show()